[workspace]
members = ["contracts/ckb-combine-lock", "contracts/child-script-example", "contracts/child-script-always-success"]

[profile.release]
overflow-checks = true
opt-level = 3
panic = 'abort'
strip = true

